name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Commit files
      run: |
        cd build
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote add origin git@github.com:kju8/all-embracing-insane-charts.git
        git add table.json
        git commit -m "build"
        git push origin master:build